### PR TITLE
Data loader

### PR DESCRIPTION
**Pull request by the-astronot**
Data Loader Mk1 Complete!
Ready for testing.

### CODE REVIEW

**Review by OhadNir — COMMENTED** [review]
Looks good, just a couple things to add. Images read through opencv are formatted as BGR. You'll want to change this to RGB as the RPN backbone was trained on this channel order. The image bounding boxes should be cast to a torch tensor of type float. 

We might want to keep the dataset out of the repository. We can include a readme in the datafolder on how to get setup with the data.

Also as a side note, I recommend checking out tqdm package for progress bars in python. Its such a useful library.

**Comment by the-astronot** [comment]
Gotcha
I added just a few files to get you started on the data, but they can be removed
All future images and folders have been blocked in the .gitignore
Will check out tqdm
I do have a readme in the data folder currently for data folder layout
Will cast bounding boxes to floats

**Comment by the-astronot** [comment]
@OhadNir is the RPN expecting float32 or float64 for the bounding box tensor?

**Comment by OhadNir** [comment]
float32

**Comment by the-astronot** [comment]
Fixed tensor float32 for bbox
Switched image from BGR to RGB

**Comment by OhadNir** [comment]
Looks good. Thanks more making those additions. You're good to merge.

**Pull request merged**
